jobs:
  - job: Build_PS_Win2016
    pool:
      vmImage: windows-latest
    steps:
    - powershell: |
        ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/out/testResults.xml'
        testRunTitle: 'PS_Win2016'
      displayName: 'Publish Test Results'

  - job: Build_PSCore_Ubuntu1604
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        pwsh -c './build.ps1 -Task Test -Bootstrap -Verbose'
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/out/testResults.xml'
        testRunTitle: 'PSCore_Ubuntu1604'
      displayName: 'Publish Test Results'

  - job: Build_PSCore_MacOS1013
    pool:
      vmImage: macOS-latest
    steps:
    - script: |
        pwsh -c './build.ps1 -Task Test -Bootstrap -Verbose'
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/out/testResults.xml'
        testRunTitle: 'PSCore_MacOS1013'
      displayName: 'Publish Test Results'
